# Everything that Rebos needs
[managers.init_pkgs]
items = [
  "rustup", # Rust toolchain installer
  "cargo",  # Rust package manager and build tool
  "yay",    # AUR helper for installing packages
  "neovim", # Modern Vim-based text editor
  "tmux",   # Terminal multiplexer
]

# Everything that Rebos needs
[managers.packages]
items = [
  "fnm", # Fast node version manager
]
