# ================================
# This file contains only system utilities like:
# Notifications, Volume Control, Bluetooth, Network Management, etc
# ================================

# Authentication: https://wiki.archlinux.org/title/Polkit
# Notifications Managers - https://wiki.archlinux.org/title/Desktop_notifications
# Volume Control - https://man.archlinux.org/man/pamixer.1.en
# Bluetooth Managers -https://wiki.archlinux.org/title/Bluetooth
# Network Manager: https://wiki.archlinux.org/title/NetworkManager
# Screen Locking: https://github.com/i3/i3lock
# Light Brightness Control:https://aur.archlinux.org/packages/light
# Brightnessctl: https://man.archlinux.org/man/brightnessctl.1.en

[managers.packages]
items = [
  "polkit-gnome",              # PolicyKit authentication agent for GNOME
  "gnome-keyring",             # Secure storage for passwords and keys
  "lxqt-policykit",            # PolicyKit authentication agent for LXQt
  "libnotify",                 # Library for sending desktop notifications
  # "dunst",                  # Lightweight notification daemon
  "pamixer",                # Command-line volume control for PulseAudio
  "networkmanager",         # Network management daemon
  "network-manager-applet", # GUI applet for NetworkManager
  "blueman",                # Bluetooth manager GUI
  "bluez",                  # Bluetooth protocol stack
  "bluez-utils",            # Bluetooth utilities (e.g., bluetoothctl)
  "i3lock",                 # Screen locker
  "brightnessctl",          # Command-line screen brightness control
  "udiskie",                # Automounting and removable drive management
  "power-profiles-daemon",  # Power Profile Daemon (e.g. balanced, performance)
]

[managers.serv_enable]
items = [
  "NetworkManager",        # Enable NetworkManager service at startup
  "power-profiles-daemon", # Enable Power Profile Daemon
]
