# --------------------------- #
#    Work Related Packages    #
# --------------------------- #

[managers.packages]
items = [
  "go",                  # Golang
  "migrate",             # Migrate package for database migration with sql files
  "fnm",                 # Fast and simple node version manaager
  "serpl",               # Search and Replace through terminal
  "docker",              # Containerization platform
  "docker-compose",      # Tool for defining and running multi-container Docker apps
  "gpu-screen-recorder", # Screen Recording 
  "slurp",               # Region Selection: for region recording
  "qutebrowser",         # Keyboard driven minial sleep browser
]

[managers.serv_start]
items = [
  "docker", # Start Docker daemon at login
]
