"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = 'â–¶â–¶ '
add_newline = false
command_timeout = 1000

format = """
$character\
$username\
$hostname$os\
$directory\
$git_branch \
$python\
$aws\
$golang\
$java\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$docker_context\
$cmd_duration
[â””â”€>](bold green) """

right_format = """${custom.filescount}"""

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#88d6ba'
color2 = '#00382a'
color3 = '#bfc9c3'
color4 = '#1b211e'
color5 = '#00382a'
color6 = '#0f1512'
color7 = '#0f1512'
color8 = '#88d6ba'
color9 = '#a8cce1'

[custom.filescount]
style = "dimmed"
command = "ls -a | wc -l"
detect_extensions = ["md","mdx",'ts',"tsx","js","jsx","jpg","png","webp","avif","mp4","mkv"]
detect_files = [".bashrc"]
detect_folders = ["/mnt/storage","/"]
format = "[$output]($style)"

[username]
style_user = 'purple italic'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Prompt symbols 
[character]
success_symbol = "ğŸŒ¿"
error_symbol = "ğŸ”¥"
# success_symbol = "[ğŸˆ](color9 bold)"
# error_symbol = "[ğŸˆ](@{error})"
vicmd_symbol = "[ğŸˆ](#f9e2af)"

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#1d2230"
# format = '[[ ó±‘ $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
format = "[î‚¶](fg:color8 bg:color4)[ïº ](bg:color8 fg:color5)[î‚´](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[î‚´](fg:color4) "

[cmd_duration]
format = 'last command: [$duration](bold yellow)'
show_milliseconds = true

# ---

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
EndeavourOS = "ïŒ¢ "

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](italic yellow) '
disabled = false
ssh_symbol = "î¬ "

# Shows current directory
[directory]
truncation_length = 3
fish_style_pwd_dir_length=2
home_symbol = 'ó°‹œ '
read_only_style = '197'
read_only = ' ï€£ '
format = 'at [$path]($style)[$read_only]($read_only_style) '
# format = "[î‚¶](fg:color1 bg:color4)[ó°‰‹](bg:color1 fg:color2)[î‚´ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[î‚´ ](fg:color4)"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
'/mnt/storage/workspace/goenv/src/github.com/sirjager' = 'î˜§ ' # î˜§ î™
'/mnt/storage/workspace/apps' = 'ï„‹ ' # ï…» î¬©
'/mnt/storage/workspace/rust' = 'îš‹ '
'/mnt/storage/workspace/web' = 'î¬ '
'/mnt/storage/workspace/projects' = 'î¯Ÿ '
'/mnt/storage/workspace/cli' = 'î¯‡ '
'/mnt/storage/workspace/scripts' = 'ï“­ '
'/mnt/storage/workspace/notes' = 'î®¯ ' # î®¯
'/mnt/storage/workspace/api' = 'î« '
'/mnt/storage/workspace/stacks' = 'ï” '  # ï‘³
'/mnt/storage/workspace' = 'ï‚± ' # ïƒ²
'/mnt/storage/wallpaper' = 'ï€¾ '
'/mnt/storage/programs' = 'î¬© '
'/mnt/storage/softwares' = 'îª˜ '
'/mnt/storage' = 'ï‚  '

# Shows current git branch
[git_branch]
symbol = "ï˜ "
format = 'via [$symbol$branch]($style)'
# format = "[î‚¶](fg:color8 bg:color4)[ï‡“ ](bg:color8 fg:color5)[î‚´](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[î‚´](fg:color4) "
# truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'italic green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'italic green'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
staged = '[++\($count\)](green)'
renamed = 'ïª¶ '
deleted = 'ï€” '



[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[golang]
symbol = "î˜§ "

[java]
symbol = "î‰– "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ó°— "

[pijul_channel]
symbol = "ï˜ "

[python]
symbol = "îˆµ "
pyenv_prefix = 'venv'
pyenv_version_name = true
# format = "[î‚¶](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[î‚´](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[î‚´](fg:color4) "

[ruby]
symbol = "î‘ "

[rlang]
symbol = "ó°Ÿ” "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

