# : Manager [[[

[manager]
cwd = { fg = "#e1e2e8" }

# Tab
tab_active = { fg = "#003258", bg = "#a0cafd", bold = true }
tab_inactive = { fg = "#d1e4ff", bg = "#001d36" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ce74ff", bg = "#ce74ff" }
marker_cut = { fg = "#f2daff", bg = "#f2daff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d6bee4", bg = "#d6bee4" }

# Count
count_copied = { fg = "#251432", bg = "#f2daff" }
count_cut = { fg = "#251432", bg = "#f2daff" }
count_selected = { fg = "#003258", bg = "#d6bee4" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#a0cafd" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003258", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a0cafd", fg = "#003258", bold = true }
normal_alt  = { bg = "#42474e", fg = "#c3c7cf" }

# Select mode
select_main = { bg = "#bac7db", fg = "#253140", bold = true }
select_alt  = { bg = "#42474e", fg = "#c3c7cf" }

# Unset mode
unset_main = { bg = "#d6bee4", fg = "#3b2948", bold = true }
unset_alt  = { bg = "#42474e", fg = "#c3c7cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a0cafd", bg = "#36393e" }
progress_error = { fg = "#ffb4ab", bg = "#36393e" }

# Permissions
permissions_t = { fg = "#5676a6" }
permissions_w = { fg = "#9252b7" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#bc41ff" }
permissions_s = { fg = "#388aff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a0cafd" }
active = { fg = "#d6bee4", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#a0cafd" }
value = { fg = "#e1e2e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a0cafd", bg = "#003258" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a0cafd" }
title = {}
hovered = { fg = "#f2daff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#36393e" }
cand = { fg = "#a0cafd" }
rest = { fg = "#003258" }
desc = { fg = "#e1e2e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e2e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e8" }
run = { fg = "#e1e2e8" }
footer = { fg = "#253140", bg = "#bac7db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d6bee4" }
title_warn = { fg = "#a0cafd" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e8" },
    { name = "*/", fg = "#a0cafd" },
]

# : ]]]
