# : Manager [[[

[manager]
cwd = { fg = "#dde3ea" }

# Tab
tab_active = { fg = "#373100", bg = "#d7c866", bold = true }
tab_inactive = { fg = "#f4e47f", bg = "#201c00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#60bcff", bg = "#60bcff" }
marker_cut = { fg = "#c6e7ff", bg = "#c6e7ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#9bcdef", bg = "#9bcdef" }

# Count
count_copied = { fg = "#001e2e", bg = "#c6e7ff" }
count_cut = { fg = "#001e2e", bg = "#c6e7ff" }
count_selected = { fg = "#373100", bg = "#9bcdef" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#d7c866" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#373100", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#d7c866", fg = "#373100", bold = true }
normal_alt  = { bg = "#3c4851", fg = "#bcc8d3" }

# Select mode
select_main = { bg = "#d6bee5", fg = "#3b2948", bold = true }
select_alt  = { bg = "#3c4851", fg = "#bcc8d3" }

# Unset mode
unset_main = { bg = "#9bcdef", fg = "#00344b", bold = true }
unset_alt  = { bg = "#3c4851", fg = "#bcc8d3" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d7c866", bg = "#333a3f" }
progress_error = { fg = "#ffb4ab", bg = "#333a3f" }

# Permissions
permissions_t = { fg = "#9151b9" }
permissions_w = { fg = "#2189d0" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#2da7ff" }
permissions_s = { fg = "#c9b011" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d7c866" }
active = { fg = "#9bcdef", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d7c866" }
value = { fg = "#dde3ea" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d7c866", bg = "#373100" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d7c866" }
title = {}
hovered = { fg = "#c6e7ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#333a3f" }
cand = { fg = "#d7c866" }
rest = { fg = "#373100" }
desc = { fg = "#dde3ea" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dde3ea" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dde3ea" }
run = { fg = "#dde3ea" }
footer = { fg = "#3b2948", bg = "#d6bee5" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#9bcdef" }
title_warn = { fg = "#d7c866" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dde3ea" },
    { name = "*/", fg = "#d7c866" },
]

# : ]]]
