# : Manager [[[

[manager]
cwd = { fg = "#e8e0eb" }

# Tab
tab_active = { fg = "#00382a", bg = "#7dd7b9", bold = true }
tab_inactive = { fg = "#99f4d4", bg = "#002117" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ce74ff", bg = "#ce74ff" }
marker_cut = { fg = "#f2daff", bg = "#f2daff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dbbaf1", bg = "#dbbaf1" }

# Count
count_copied = { fg = "#28103b", bg = "#f2daff" }
count_cut = { fg = "#28103b", bg = "#f2daff" }
count_selected = { fg = "#00382a", bg = "#dbbaf1" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#7dd7b9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00382a", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#7dd7b9", fg = "#00382a", bold = true }
normal_alt  = { bg = "#4b4452", fg = "#cec3d4" }

# Select mode
select_main = { bg = "#e5bad8", fg = "#44263e", bold = true }
select_alt  = { bg = "#4b4452", fg = "#cec3d4" }

# Unset mode
unset_main = { bg = "#dbbaf1", fg = "#3e2652", bold = true }
unset_alt  = { bg = "#4b4452", fg = "#cec3d4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7dd7b9", bg = "#3c3740" }
progress_error = { fg = "#ffb4ab", bg = "#3c3740" }

# Permissions
permissions_t = { fg = "#bb4b99" }
permissions_w = { fg = "#993bd7" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#bc41ff" }
permissions_s = { fg = "#18dc97" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#7dd7b9" }
active = { fg = "#dbbaf1", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#7dd7b9" }
value = { fg = "#e8e0eb" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#7dd7b9", bg = "#00382a" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7dd7b9" }
title = {}
hovered = { fg = "#f2daff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c3740" }
cand = { fg = "#7dd7b9" }
rest = { fg = "#00382a" }
desc = { fg = "#e8e0eb" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e8e0eb" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e8e0eb" }
run = { fg = "#e8e0eb" }
footer = { fg = "#44263e", bg = "#e5bad8" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#dbbaf1" }
title_warn = { fg = "#7dd7b9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e8e0eb" },
    { name = "*/", fg = "#7dd7b9" },
]

# : ]]]
