# : Manager [[[

[manager]
cwd = { fg = "#dee3eb" }

# Tab
tab_active = { fg = "#2f3300", bg = "#c5cd70", bold = true }
tab_inactive = { fg = "#e2e989", bg = "#1b1d00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#69aeff", bg = "#69aeff" }
marker_cut = { fg = "#cfe5ff", bg = "#cfe5ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a4caf5", bg = "#a4caf5" }

# Count
count_copied = { fg = "#001d34", bg = "#cfe5ff" }
count_cut = { fg = "#001d34", bg = "#cfe5ff" }
count_selected = { fg = "#2f3300", bg = "#a4caf5" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#c5cd70" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#2f3300", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c5cd70", fg = "#2f3300", bold = true }
normal_alt  = { bg = "#3f4852", fg = "#bec7d4" }

# Select mode
select_main = { bg = "#debcdf", fg = "#402843", bold = true }
select_alt  = { bg = "#3f4852", fg = "#bec7d4" }

# Unset mode
unset_main = { bg = "#a4caf5", fg = "#003355", bold = true }
unset_alt  = { bg = "#3f4852", fg = "#bec7d4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c5cd70", bg = "#353a40" }
progress_error = { fg = "#ffb4ab", bg = "#353a40" }

# Permissions
permissions_t = { fg = "#ab54ae" }
permissions_w = { fg = "#1a7ae6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3692ff" }
permissions_s = { fg = "#acb722" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c5cd70" }
active = { fg = "#a4caf5", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c5cd70" }
value = { fg = "#dee3eb" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c5cd70", bg = "#2f3300" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c5cd70" }
title = {}
hovered = { fg = "#cfe5ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a40" }
cand = { fg = "#c5cd70" }
rest = { fg = "#2f3300" }
desc = { fg = "#dee3eb" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee3eb" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3eb" }
run = { fg = "#dee3eb" }
footer = { fg = "#402843", bg = "#debcdf" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a4caf5" }
title_warn = { fg = "#c5cd70" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3eb" },
    { name = "*/", fg = "#c5cd70" },
]

# : ]]]
